server:
  port: 8081
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: mailtestcjh@gmail.com
    password: xohvhfpztqxdzaqo
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/NarangNorang?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul&useOldAliasMetadataBehavior=true&zeroDateTimeNehavior=convertToNull
    username: root
    password: 
mybatis:
  type-aliases-package: com.example.demo.vo
custom:
  siteName: NarangNorang
  siteMainUri: http://localhost:8081
  emailFrom: no-reply@localhost
  emailFromName: NarangNorang
koreaTourApi:
  baseUrl: https://api.visitkorea.or.kr/openapi/service/rest
  apiKey: etI7sqqHopSpi3JZauJxFkgDNo3uV2a7YM6K%2FwVIiQUaoEwp38zVrbJrT01gkXxKobHJA8vBQnjdk6VWYGfmMw%3D%3D